CREATE TABLE IF NOT EXISTS vozidlo (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  spz TEXT NOT NULL UNIQUE,
  majitel TEXT,
  typ_vozidla TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS rezervace (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  vozidlo_id INTEGER NOT NULL,
  misto_id INTEGER NOT NULL,
  datum_od TEXT NOT NULL,
  datum_do TEXT NOT NULL,
  FOREIGN KEY (vozidlo_id) REFERENCES vozidlo(id),
  FOREIGN KEY (misto_id) REFERENCES misto(id)
);

CREATE TABLE IF NOT EXISTS misto (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cislo_mista INTEGER NOT NULL UNIQUE,
  obsazeno TEXT
);
